#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

cidfile="$1"
cid="$(<"$cidfile")"

# Stop the old container (or be cool if it's already stopped)
docker stop "$cid" > /dev/null || :

# Block until that container is done
docker wait "$cid" > /dev/null

# Remove the old container
docker rm "$cid" > /dev/null
rm "$cidfile"
