#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

cidfile="$1"
cid="$(<"$cidfile")"

# Ensure the container is stopped
docker stop "$cid" > /dev/null

# Remove the container
docker rm "$cid" > /dev/null
rm "$cidfile"
